apiVersion: v1
kind: ResourceQuota
metadata:
  name: observability
  namespace: observability-peer
spec:
  hard:
    pods: 1G
  scopeSelector:
  - operator: In
    scopeName: PriorityClass
    values:
    - system-node-critical
    - system-cluster-critical
